### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by dfhoughton** [dfhoughton/amanuensis-2#1]
This is a list of things I mean to do. I'm writing them down so I won't keep rediscovering them in the wee hours of the morning when I should be sleeping.

- [ ] save both free form and similarity searches
- [ ] improve phrase and citation lists
- [ ] get goto working
- [ ] add relations
- [ ] announce possible phrases to merge a citation with
- [ ] polish the help text
- [ ] add about information somewhere
- [ ] phrase merging
- [ ] citation moving
- [ ] get updated_at working correctly for phrases
- [ ] add sort by recency to search results
